#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "Cedexis.h"
#import "DelegatesArray.h"
#import "IBandAbstractPlayer+Internal.h"
#import "IBandAbstractPlayer.h"
#import "IBandApi.h"
#import "IBandDelegatable.h"
#import "IBandDelegate.h"
#import "IBandDisposable.h"
#import "IBandError+Internal.h"
#import "IBandError.h"
#import "IBandEvent+Internal.h"
#import "IBandEvent.h"
#import "IBandInteraction+Protected.h"
#import "IBandInteraction.h"
#import "IBandInteractionView.h"
#import "IBandM3U8Parser.h"
#import "IBandMacros.h"
#import "IBandMessage.h"
#import "IBandNetworkGetaway.h"
#import "IBandPlayer+Internal.h"
#import "IBandPlayer.h"
#import "IBandPlayerEvent.h"
#import "IBandPlayerManager+Internal.h"
#import "IBandPlayerManager.h"
#import "IBandPlayerSDK.h"
#import "IBandPlayerVariant.h"
#import "IBandPlayerView+Internal.h"
#import "IBandPlayerView.h"
#import "IBandPlayerViewDelegate.h"
#import "IBandSDK+Internal.h"
#import "IBandSDK.h"
#import "IBandSession+Internal.h"
#import "IBandSession.h"
#import "IBandSocket.h"
#import "IBandSource+Internal.h"
#import "IBandSource.h"
#import "IBandStream+Internal.h"
#import "IBandStream.h"
#import "IBandStreamStatus.h"
#import "IBandThumbnail.h"
#import "IBandUtils.h"
#import "IBandViewModel.h"
#import "IBandWatchable+Internal.h"
#import "IBandWatchable.h"
#import "IBandWatcher.h"
#import "IEvents.h"
#import "CardboardDeviceParams.h"
#import "CardboardSDK.h"
#import "CardboardUnity.h"
#import "CBDStereoGLView.h"
#import "CBDViewController.h"
#import "DebugUtils.h"
#import "Distortion.h"
#import "DistortionRenderer.h"
#import "Eye.h"
#import "FieldOfView.h"
#import "GLHelpers.h"
#import "GLStateBackup.h"
#import "HeadMountedDisplay.h"
#import "HeadTracker.h"
#import "HeadTransform.h"
#import "MagnetSensor.h"
#import "Matrix3x3d.h"
#import "OrientationEKF.h"
#import "ScreenParams.h"
#import "SO3Util.h"
#import "Vector3d.h"
#import "Viewport.h"
#import "M3U8ExtXMedia.h"
#import "M3U8ExtXMediaList.h"
#import "M3U8ExtXStreamInf.h"
#import "M3U8ExtXStreamInfList.h"
#import "M3U8Kit.h"
#import "M3U8MasterPlaylist.h"
#import "M3U8MediaPlaylist.h"
#import "M3U8PlaylistModel.h"
#import "M3U8SegmentInfo.h"
#import "M3U8SegmentInfoList.h"
#import "M3U8TagsAndAttributes.h"
#import "NSString+m3u8.h"
#import "NSURL+easy.h"
#import "CardboardViewController.h"
#import "GLProgram.h"
#import "HTYGLKVC.h"
#import "VideoRenderer.h"
#import "TimerTarget.h"
#import "IDeviceInfo.h"
#import "YBPlayer.h"
#import "YBPlayerError.h"
#import "YBPlayerUtils.h"
#import "Varinat.h"

FOUNDATION_EXPORT double IBandPlayerSDKVersionNumber;
FOUNDATION_EXPORT const unsigned char IBandPlayerSDKVersionString[];

